<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VoiceDuck.Core\VoiceDuck.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="VoiceDuck.Extensions.WindowsAudio.Tests" />
  </ItemGroup>

</Project>